import type { NextPage } from "next";
import Head from "next/head";
import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const resultQuery = trpc.logs.getLast10.useQuery();

  return (
    <>
      <Head>
        <title>SolarSystem</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        
      </main>
     </>
  );
};

export default Home;
