services:
  collector:
    image: "ghcr.io/gabryjiel/solar-system/collector:master"
    container_name: collector
    stdin_open: true
    tty: true
    environment:
      - FREQ=${FREQ}
      - STATUS_URL=${STATUS_URL}
      - DB_URL=postgres://${DB_USER}:${DB_PASSWORD}@database?sslmode=disable
      - AUTH_USER=${AUTH_USER}
      - AUTH_PASSWORD=${AUTH_PASSWORD}
    depends_on:
      - database

  database:
    image: "postgres:17.2-alpine3.21"
    container_name: db
    shm_size: 128mb
    stdin_open: true
    tty: true
    restart: always
    ports:
      - 5555:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - "~/pgdata:/var/lib/postgresql/data"
